services:
  db:
    profiles:
      - prod
      - dev
    ports:
      - "5432:5432"   # accès DBeaver/pgAdmin en local uniquement

  backend-dev:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
      target: dev
    container_name: aireviewhub-backend-dev
    profiles:
      - dev
    ports:
      - "${BACKEND_PORT}:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=${CONNECTION_STRING}
      - Jwt__Key=${JWT_KEY}
      - Google__ClientId=${GOOGLE_CLIENT_ID}
      - Google__ClientSecret=${GOOGLE_CLIENT_SECRET}
      - OpenAI__ApiKey=${OPENAI_API_KEY}
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - aireviewhub-network


  angular-dev:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
      target: dev
    container_name: aireviewhub-angular-dev
    profiles:
      - dev
    ports:
      - "4200:4200"
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    depends_on:
      backend-dev:
        condition: service_started
    networks:
      - aireviewhub-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: aireviewhub-pgadmin
    profiles:
      - dev
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - aireviewhub-network
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  
  widget:
    image: nginx:alpine
    profiles:
      - dev
      - prod
    volumes:
      - ./widget/dist:/usr/share/nginx/html:ro
    ports:
      - "3000:80"
    networks:
      - aireviewhub-network

  stripe-cli:
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    profiles:
      - dev
    command: listen --forward-to http://backend:8080/api/webhook
    environment:
      - STRIPE_API_KEY=${STRIPE_SECRET_KEY}
    volumes:
      - stripe-config:/root/.config/stripe
    networks:
      - aireviewhub-network

volumes:
  pgadmin-data:
  stripe-config: